insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('nextjs','Next.js','framework','nextdotjs','https://nextjs.org',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','next',null,null from technologies where slug='nextjs';
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'file',null,'next.config.*',null,null from technologies where slug='nextjs';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('react','React','framework','react','https://react.dev',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','react',null,null from technologies where slug='react';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('vue','Vue','framework','vuedotjs','https://vuejs.org',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','vue',null,null from technologies where slug='vue';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('nuxt','Nuxt','framework','nuxt','https://nuxt.com',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','nuxt',null,null from technologies where slug='nuxt';
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'file',null,'nuxt.config.*',null,null from technologies where slug='nuxt';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('svelte','Svelte','framework','svelte','https://svelte.dev',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','svelte',null,null from technologies where slug='svelte';
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','@sveltejs/kit',null,null from technologies where slug='svelte';
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'file',null,'svelte.config.*',null,null from technologies where slug='svelte';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('astro','Astro','framework','astro','https://astro.build',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','astro',null,null from technologies where slug='astro';
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'file',null,'astro.config.*',null,null from technologies where slug='astro';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('remix','Remix','framework','remix','https://remix.run',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','@remix-run/*',null,null from technologies where slug='remix';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('express','Express','framework','express','https://expressjs.com',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','express',null,null from technologies where slug='express';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('fastify','Fastify','framework','fastify','https://fastify.dev',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','fastify',null,null from technologies where slug='fastify';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('hono','Hono','framework','hono','https://hono.dev',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','hono',null,null from technologies where slug='hono';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('nestjs','NestJS','framework','nestjs','https://nestjs.com',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','@nestjs/core',null,null from technologies where slug='nestjs';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('django','Django','framework','django','https://www.djangoproject.com',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','pypi','django',null,null from technologies where slug='django';
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'file',null,'manage.py',null,null from technologies where slug='django';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('fastapi','FastAPI','framework','fastapi','https://fastapi.tiangolo.com',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','pypi','fastapi',null,null from technologies where slug='fastapi';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('flask','Flask','framework','flask','https://flask.palletsprojects.com',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','pypi','flask',null,null from technologies where slug='flask';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('rails','Ruby on Rails','framework','rubyonrails','https://rubyonrails.org',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','gem','rails',null,null from technologies where slug='rails';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('laravel','Laravel','framework','laravel','https://laravel.com',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','composer','laravel/framework',null,null from technologies where slug='laravel';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('gin','Gin','framework','gin','https://gin-gonic.com',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','go','github.com/gin-gonic/gin',null,null from technologies where slug='gin';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('spring','Spring','framework','spring','https://spring.io',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','maven','org.springframework*',null,null from technologies where slug='spring';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('typescript','TypeScript','language','typescript','https://www.typescriptlang.org',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','typescript',null,null from technologies where slug='typescript';
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'file',null,'tsconfig.json',null,null from technologies where slug='typescript';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('python','Python','language','python','https://python.org',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'file',null,'pyproject.toml',null,null from technologies where slug='python';
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'file',null,'requirements.txt',null,null from technologies where slug='python';
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'file',null,'setup.py',null,null from technologies where slug='python';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('go','Go','language','go','https://go.dev',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'file',null,'go.mod',null,null from technologies where slug='go';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('rust','Rust','language','rust','https://rust-lang.org',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'file',null,'Cargo.toml',null,null from technologies where slug='rust';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('php','PHP','language','php','https://php.net',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'file',null,'composer.json',null,null from technologies where slug='php';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('ruby','Ruby','language','ruby','https://ruby-lang.org',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'file',null,'Gemfile',null,null from technologies where slug='ruby';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('java','Java','language','openjdk','https://openjdk.org',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'file',null,'pom.xml',null,null from technologies where slug='java';
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'file',null,'build.gradle*',null,null from technologies where slug='java';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('bun','Bun','language','bun','https://bun.sh',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'file',null,'bun.lockb',null,null from technologies where slug='bun';
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'file',null,'bun.lock',null,null from technologies where slug='bun';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('deno','Deno','language','deno','https://deno.com',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'file',null,'deno.json',null,null from technologies where slug='deno';
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'file',null,'deno.jsonc',null,null from technologies where slug='deno';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('tailwind','Tailwind CSS','styling','tailwindcss','https://tailwindcss.com','https://tailwindcss.com/llms.txt',null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','tailwindcss',null,null from technologies where slug='tailwind';
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'file',null,'tailwind.config.*',null,null from technologies where slug='tailwind';
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'config-pattern',null,'@tailwindcss/postcss','postcss.config.*','major>=4' from technologies where slug='tailwind';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('shadcn','shadcn/ui','styling','shadcnui','https://ui.shadcn.com',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'file',null,'components.json',null,null from technologies where slug='shadcn';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('radix','Radix UI','styling','radixui','https://www.radix-ui.com',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','@radix-ui/*',null,null from technologies where slug='radix';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('mui','MUI','styling','mui','https://mui.com',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','@mui/material',null,null from technologies where slug='mui';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('chakra','Chakra UI','styling','chakraui','https://chakra-ui.com',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','@chakra-ui/react',null,null from technologies where slug='chakra';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('styled-components','styled-components','styling','styledcomponents','https://styled-components.com',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','styled-components',null,null from technologies where slug='styled-components';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('sass','Sass','styling','sass','https://sass-lang.com',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','sass',null,null from technologies where slug='sass';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('framer-motion','Framer Motion','styling','framer','https://motion.dev',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','framer-motion',null,null from technologies where slug='framer-motion';
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','motion',null,null from technologies where slug='framer-motion';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('supabase','Supabase','database','supabase','https://supabase.com',null,'{"command":"npx","args":["-y","@supabase/mcp-server-supabase"]}'::jsonb) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','@supabase/supabase-js',null,null from technologies where slug='supabase';
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'file',null,'supabase/**',null,null from technologies where slug='supabase';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('prisma','Prisma','database','prisma','https://prisma.io',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','prisma',null,null from technologies where slug='prisma';
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','@prisma/client',null,null from technologies where slug='prisma';
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'file',null,'prisma/schema.prisma',null,null from technologies where slug='prisma';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('drizzle','Drizzle ORM','database','drizzle','https://orm.drizzle.team',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','drizzle-orm',null,null from technologies where slug='drizzle';
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'file',null,'drizzle.config.*',null,null from technologies where slug='drizzle';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('mongoose','Mongoose','database','mongoose','https://mongoosejs.com',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','mongoose',null,null from technologies where slug='mongoose';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('sqlalchemy','SQLAlchemy','database','sqlalchemy','https://sqlalchemy.org',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','pypi','sqlalchemy',null,null from technologies where slug='sqlalchemy';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('postgres','PostgreSQL','database','postgresql','https://postgresql.org',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','pg',null,null from technologies where slug='postgres';
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','pypi','psycopg2',null,null from technologies where slug='postgres';
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','pypi','psycopg',null,null from technologies where slug='postgres';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('mysql','MySQL','database','mysql','https://mysql.com',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','mysql2',null,null from technologies where slug='mysql';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('sqlite','SQLite','database','sqlite','https://sqlite.org',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','better-sqlite3',null,null from technologies where slug='sqlite';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('redis','Redis','database','redis','https://redis.io',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','redis',null,null from technologies where slug='redis';
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','ioredis',null,null from technologies where slug='redis';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('upstash','Upstash','database','upstash','https://upstash.com',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','@upstash/redis',null,null from technologies where slug='upstash';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('nextauth','Auth.js','auth','auth0','https://authjs.dev',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','next-auth',null,null from technologies where slug='nextauth';
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','@auth/*',null,null from technologies where slug='nextauth';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('clerk','Clerk','auth','clerk','https://clerk.com',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','@clerk/*',null,null from technologies where slug='clerk';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('better-auth','Better Auth','auth',null,'https://better-auth.com',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','better-auth',null,null from technologies where slug='better-auth';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('lucia','Lucia','auth',null,'https://lucia-auth.com',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','lucia',null,null from technologies where slug='lucia';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('vitest','Vitest','testing','vitest','https://vitest.dev',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','vitest',null,null from technologies where slug='vitest';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('jest','Jest','testing','jest','https://jestjs.io',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','jest',null,null from technologies where slug='jest';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('playwright','Playwright','testing','playwright','https://playwright.dev',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','@playwright/test',null,null from technologies where slug='playwright';
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','playwright',null,null from technologies where slug='playwright';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('cypress','Cypress','testing','cypress','https://cypress.io',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','cypress',null,null from technologies where slug='cypress';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('pytest','pytest','testing','pytest','https://pytest.org',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','pypi','pytest',null,null from technologies where slug='pytest';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('testing-library','Testing Library','testing','testinglibrary','https://testing-library.com',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','@testing-library/*',null,null from technologies where slug='testing-library';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('docker','Docker','infra','docker','https://docker.com',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'file',null,'Dockerfile',null,null from technologies where slug='docker';
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'file',null,'docker-compose*',null,null from technologies where slug='docker';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('vercel','Vercel','infra','vercel','https://vercel.com',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'file',null,'vercel.json',null,null from technologies where slug='vercel';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('turborepo','Turborepo','tooling','turborepo','https://turborepo.dev',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','turbo',null,null from technologies where slug='turborepo';
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'file',null,'turbo.json',null,null from technologies where slug='turborepo';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('nx','Nx','tooling','nx','https://nx.dev',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','nx',null,null from technologies where slug='nx';
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'file',null,'nx.json',null,null from technologies where slug='nx';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('pnpm','pnpm','tooling','pnpm','https://pnpm.io',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'file',null,'pnpm-lock.yaml',null,null from technologies where slug='pnpm';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('yarn','Yarn','tooling','yarn','https://yarnpkg.com',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'file',null,'yarn.lock',null,null from technologies where slug='yarn';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('npm','npm','tooling','npm','https://npmjs.com',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'file',null,'package-lock.json',null,null from technologies where slug='npm';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('eslint','ESLint','tooling','eslint','https://eslint.org',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','eslint',null,null from technologies where slug='eslint';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('prettier','Prettier','tooling','prettier','https://prettier.io',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','prettier',null,null from technologies where slug='prettier';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('biome','Biome','tooling','biome','https://biomejs.dev',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','@biomejs/biome',null,null from technologies where slug='biome';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('storybook','Storybook','tooling','storybook','https://storybook.js.org',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','storybook',null,null from technologies where slug='storybook';
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'file',null,'.storybook/**',null,null from technologies where slug='storybook';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('trpc','tRPC','tooling','trpc','https://trpc.io',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','@trpc/*',null,null from technologies where slug='trpc';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('zod','Zod','tooling','zod','https://zod.dev',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','zod',null,null from technologies where slug='zod';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('stripe','Stripe','tooling','stripe','https://stripe.com',null,'{"command":"npx","args":["-y","@stripe/mcp","--tools=all"]}'::jsonb) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','stripe',null,null from technologies where slug='stripe';
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','pypi','stripe',null,null from technologies where slug='stripe';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('sentry','Sentry','tooling','sentry','https://sentry.io',null,'{"command":"npx","args":["-y","@sentry/mcp-server"]}'::jsonb) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','@sentry/*',null,null from technologies where slug='sentry';
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','pypi','sentry-sdk',null,null from technologies where slug='sentry';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('inngest','Inngest','tooling','inngest','https://inngest.com',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','inngest',null,null from technologies where slug='inngest';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('anthropic','Anthropic SDK','ai','anthropic','https://docs.anthropic.com','https://docs.anthropic.com/llms.txt',null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','@anthropic-ai/sdk',null,null from technologies where slug='anthropic';
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','pypi','anthropic',null,null from technologies where slug='anthropic';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('openai','OpenAI SDK','ai','openai','https://platform.openai.com',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','openai',null,null from technologies where slug='openai';
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','pypi','openai',null,null from technologies where slug='openai';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('vercel-ai','Vercel AI SDK','ai','vercel','https://sdk.vercel.ai','https://sdk.vercel.ai/llms.txt',null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','ai',null,null from technologies where slug='vercel-ai';
insert into technologies (slug,name,category,icon_ref,homepage,llms_txt_url,mcp_server_json) values ('langchain','LangChain','ai','langchain','https://langchain.com',null,null) on conflict (slug) do nothing;
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','langchain',null,null from technologies where slug='langchain';
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','npm','@langchain/*',null,null from technologies where slug='langchain';
insert into detection_rules (technology_id,rule_type,ecosystem,pattern,target_file_glob,version_hint) select id,'dependency','pypi','langchain',null,null from technologies where slug='langchain';
