import type { CanonicalBrief } from "@/lib/generate/brief";
import type { FactSheet } from "@/lib/generate/factsheet";
import type { DetectionResult } from "@/lib/detect/types";
import { TECH_BY_SLUG } from "@/lib/detect/registry";

/**
 * Format writers — pure functions (02 §7.5). Interface takes
 * (brief, facts, detection) so future Windsurf/Gemini writers plug in.
 */

function commandsSection(brief: CanonicalBrief): string {
  const entries = Object.entries(brief.commands);
  if (entries.length === 0) return "";
  return entries.map(([name, cmd]) => `- \`${cmd}\` — ${name}`).join("\n");
}

function structureSection(brief: CanonicalBrief): string {
  return brief.structure_highlights
    .map((h) => `- \`${h.path}\`${h.description ? ` — ${h.description}` : ""}`)
    .join("\n");
}

function staleHeader(facts: FactSheet): string {
  const audit = facts.existingConfigAudit[0];
  if (!audit || audit.staleClaims.length === 0) return "";
  return `> Replaces stale ${audit.file} (${audit.staleClaims.length} outdated references)\n\n`;
}

function stackSection(facts: FactSheet): string {
  const byCategory = new Map<string, string[]>();
  for (const tech of facts.techList) {
    const label = tech.version ? `${tech.name} ${tech.version}` : tech.name;
    const list = byCategory.get(tech.category) ?? [];
    list.push(label);
    byCategory.set(tech.category, list);
  }
  return [...byCategory.entries()]
    .map(([category, items]) => `- **${category}:** ${items.join(" · ")}`)
    .join("\n");
}

export function writeAgentsMd(
  brief: CanonicalBrief,
  facts: FactSheet,
): string {
  const sections = [
    `# ${facts.repo.owner}/${facts.repo.name} — Agent Guide`,
    "",
    staleHeader(facts) + brief.overview,
    "",
    "## Stack",
    stackSection(facts),
  ];
  const commands = commandsSection(brief);
  if (commands) sections.push("", "## Commands", commands);
  if (brief.structure_highlights.length > 0) {
    sections.push("", "## Structure", structureSection(brief));
  }
  if (facts.workspaceTopology.length > 0) {
    sections.push(
      "",
      "## Workspaces",
      facts.workspaceTopology
        .map((ws) => `- \`${ws.path}\`${ws.name ? ` (${ws.name})` : ""}`)
        .join("\n"),
    );
  }
  if (brief.architecture_notes.length > 0) {
    sections.push(
      "",
      "## Architecture",
      brief.architecture_notes
        .map((n) => `- ${n.note} (see \`${n.evidence}\`)`)
        .join("\n"),
    );
  }
  if (brief.conventions.length > 0) {
    sections.push(
      "",
      "## Conventions",
      brief.conventions
        .map((c) => `- ${c.rule} (see \`${c.evidence}\`)`)
        .join("\n"),
    );
  }
  if (brief.gotchas.length > 0) {
    sections.push("", "## Gotchas", brief.gotchas.map((g) => `- ${g}`).join("\n"));
  }
  return sections.join("\n") + "\n";
}

/** Same content, CC conventions: commands first, ≤120 lines target. */
export function writeClaudeMd(brief: CanonicalBrief, facts: FactSheet): string {
  const sections = [
    `# CLAUDE.md — ${facts.repo.owner}/${facts.repo.name}`,
    "",
    staleHeader(facts) + brief.overview,
  ];
  const commands = commandsSection(brief);
  if (commands) sections.push("", "## Commands", commands);
  sections.push("", "## Stack", stackSection(facts));
  if (brief.structure_highlights.length > 0) {
    sections.push("", "## Structure", structureSection(brief));
  }
  if (brief.conventions.length > 0) {
    sections.push(
      "",
      "## Rules",
      brief.conventions.map((c) => `- ${c.rule} (\`${c.evidence}\`)`).join("\n"),
    );
  }
  if (brief.gotchas.length > 0) {
    sections.push("", "## Gotchas", brief.gotchas.map((g) => `- ${g}`).join("\n"));
  }
  const output = sections.join("\n") + "\n";
  // ≤120 lines target: trim structure first if over
  const lines = output.split("\n");
  return lines.length > 120 ? lines.slice(0, 120).join("\n") + "\n" : output;
}

export function writeCursorRules(
  brief: CanonicalBrief,
  facts: FactSheet,
): string {
  const body = writeAgentsMd(brief, facts)
    .split("\n")
    .slice(2) // drop the h1, frontmatter identifies it
    .join("\n");
  return `---
description: ${facts.repo.owner}/${facts.repo.name} project brief (generated by gitbrief)
alwaysApply: true
---
${body}`;
}

export function writeMcpJson(detection: DetectionResult): string | null {
  const servers: Record<string, unknown> = {};
  for (const tech of detection.techs) {
    const registryEntry = TECH_BY_SLUG.get(tech.slug);
    if (registryEntry?.mcpServerJson) {
      servers[tech.slug] = registryEntry.mcpServerJson;
    }
  }
  if (Object.keys(servers).length === 0) return null;
  return JSON.stringify({ mcpServers: servers }, null, 2) + "\n";
}

const IGNORE_CANDIDATES = [
  "node_modules",
  "dist",
  "build",
  ".next",
  "out",
  "coverage",
  ".turbo",
  "vendor",
  "__pycache__",
  ".venv",
  "venv",
  "target",
  ".cache",
  "public/assets",
  "*.lock",
];

/** Ignore file from dirs present in THIS tree only (02 §7.5). */
export function writeIgnore(treePaths: string[]): string | null {
  const topDirs = new Set(
    treePaths.filter((p) => p.includes("/")).map((p) => p.split("/")[0] ?? ""),
  );
  const lines: string[] = [];
  for (const candidate of IGNORE_CANDIDATES) {
    if (candidate === "*.lock") {
      if (treePaths.some((p) => /(^|\/)[^/]+\.lock$/.test(p))) {
        lines.push("*.lock");
      }
    } else if (topDirs.has(candidate) || candidate === "node_modules") {
      lines.push(`${candidate}/`);
    }
  }
  if (lines.length === 0) return null;
  return (
    "# Generated by gitbrief — paths AI tools should skip\n" +
    lines.join("\n") +
    "\n"
  );
}
